-- 음식 종류 별 최대값을 먼저 찾기
-- 최대값을 찾고 난 후 그거랑 일치하는거 찾기
SELECT B.FOOD_TYPE, B.REST_ID, B.REST_NAME, B.FAVORITES
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) A
JOIN REST_INFO B ON A.FOOD_TYPE = B.FOOD_TYPE AND B.FAVORITES = A.FAVORITES
ORDER BY FOOD_TYPE DESC

