-- 생산일자가 2022년 5월인 식품
SELECT O.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE DATE(PRODUCE_DATE) BETWEEN DATE('2022-05-01') AND DATE('2022-05-31')
GROUP BY PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID