-- 상반기 아이스크림 총 주문양
SELECT A.FLAVOR AS FLAVOR
FROM FIRST_HALF A
JOIN (
    -- 7월 아이스크림 총 주문양
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR) AS B
ON A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC
LIMIT 3;