-- 완료된 중고 거래의 총 금액이 70 이상인 사람 구하기
-- 이후 join하기
SELECT B.USER_ID AS USER_ID, B.NICKNAME, A.TOTAL_SALES AS TOTAL_SALES
FROM USED_GOODS_USER B
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
) A ON A.WRITER_ID = B.USER_ID AND TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES
