-- 한쪽 테이블에만 있는 정보를 얻고 싶으므로 join 사용
-- 보호 시작일(ins)보다 입양일(outs)이 더 빠른 동물 조회

SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
INNER JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME