SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE 
JOIN (
    SELECT C.FISH_TYPE, MAX(C.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO C
    GROUP BY C.FISH_TYPE
) D ON A.FISH_TYPE = D.FISH_TYPE AND A.LENGTH = D.MAX_LENGTH
